### ISSUE TITLE
2.0.0 keeps crashing

### ISSUE THREAD

**Issue by sjaakie33** [caseda/com.tkbhome#30]
Good day Caseda

thanks for rewrite to SDKv2
app since update yesterday keeps crashing

Regards
René

**Comment by sjaakie33** [comment]
crash log

(node:31837) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 __appInit listeners added. Use emitter.setMaxListeners() to increase limit
/drivers/TZ88/device.js:36
.registerRunListener(() => Promise.reject('card_not_used_anymore_use_new_reset_card');
^

SyntaxError: missing ) after argument list
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:599:28)
at Object.Module._extensions..js (module.js:646:10)
at Module.load (module.js:554:32)
at tryModuleLoad (module.js:497:12)
at Function.Module._load (module.js:489:3)
at Module.require (module.js:579:17)
at Module.require (/opt/homey-client/system/manager/ManagerApps/bootstrap/sdk/v2/index.js:1:253)
at require (internal/module.js:11:18)

Exit code: 1
Exit signal: null

**Comment by caseda** [comment]
Yup, fix is already waiting for approval by athom since yesterday evening.
Thanks for reporting though 😃

You can fix it by changing the (old) reset meter card. (you can remove the flow card even when the app is not running.)
